language: python

sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

# node 18 is not compatible with current ubuntu version used in travis
# More info about:
#   - https://travis-ci.community/t/the-command-npm-config-set-spin-false-failed-and-exited-with-1-during/12909/4
node_js:
  - 17

matrix:
  include:
    - python: 2.7
      env:
        TOXENV=pylint
    - python: 3.5
      env:
        TOXENV=pylint
    - python: 3.7
      env:
        TOXENV=pylint
    - python: 3.8
      env:
        TOXENV=pylint
        LINT="1"
        DEPLOY="1"
    - python: 3.9-dev
      env:
        TOXENV=pylint


install:
    # Remove packages installed from addons-apt-packages of travis file
    - pip install -U pip
    - sed -i '/node/d' ${TRAVIS_BUILD_DIR}/install.sh
    - sed -i '/pip install ./d' ${TRAVIS_BUILD_DIR}/install.sh

    # Install dependencies
    - ${TRAVIS_BUILD_DIR}/install.sh

    # Install testing dependencies
    - pip install -U --force-reinstall pluggy
    - pip freeze
    - pip install coveralls tox
    - if [[ "${LINT}" == "1" ]]; then pip install flake8==3.8.3 restructuredtext_lint==1.2.0 pygments; fi

script:
    - if [[ "${LINT}" == "1" ]]; then flake8 --ignore=E722,F601,F841,W503,W504,W605 --max-line-length=88 --exclude=__init__.py . && restructuredtext-lint ${TRAVIS_BUILD_DIR}/README.rst; fi
    - tox -e $TOXENV,profile-stats

after_success:
    - coveralls
    - python setup.py sdist  # Build ChangeLog file from git log

deploy:
  skip_cleanup: true  # Allow to upload Changelog generated from tox
  provider: pypi
  user: oca
  password:
    secure: hKfey6oW+K7HWxE6NJP4O9NtLnnrlofvyLAdoTk6TTA5ucqVizud7vAZN2eCu4Ftw+coTvmJLnZiy9qAREPhe3yeVyfcAOJZr4qQpH8Nzm0VKzKvOpq0L0PTFaNk1Btmmw7lbicGZsLm2qLj0dgg8pDBQ/q6U+A54gfAy3ddIAcdOP1tfdVIC1TPuSXxa8IBEec4BLE4Ao/gKoUBV9MSWyd3TgUbEycNAHHU27muhGxzEyOMW4GBgklyAjwtCzcMIPP8YW8uethCw+9nvU6q1petJYviLwM+txYrHHrgENS2yec8oFbqfXzYXprrx05BHvSdBZT5Rq2tGo02FG17FZ/HNx7g0lS7pRcyfx+8Vapf88pJdaW9rQmP90PEV5mO7EpOJ30s+xp02OIeUSkNIhIXCf9EGibW2gQynljqyuHdl1pBabBSFxA/9JICEyGEYkIRnOaKKzqBHjcpvh0AgpD/JpX5YkIc9bGjYRMiKh7bVM0JXHk1RUeC70jqAGRCObFGBF94O02POoOsRNL3+y7B+tEfbfpaSQQzqGtcfNpR/x6I5MzgNTDMGnzeUipiZM0dYaqcHdY8eAwKRMXIBVmB9JxRP+qjKtg+gSHSB4Mcmgm7hwyUWAvmxt3BnlHfF+ayyKzd0idnjGR0Gd2korndxGf0ZBbSqjkgCtPpdow=
  on:
    tags: true
    condition: $DEPLOY == "1"
    repo: OCA/pylint-odoo
